name: ci_on_self_hosted

on: [push, pull_request]

jobs:
  test-and-deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Installer les dépendances
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lancer les tests
        env:
          PYTHONPATH: src
        run: |
          python -m pytest -q

      - name: Déploiement local
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
