name: ci_on_self_hosted

on: [push, pull_request]

jobs:
  test-and-deploy:
    runs-on: [self-hosted, linux, X64]   # garde tes labels

    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v4

      - name: Installer Python (si ta VM a internet)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Créer .env pour les tests
        run: |
          echo "MONGODB_HOST=localhost" > .env
          echo "MYSQL_HOST=localhost"  >> .env
          echo "MYSQL_DB_NAME=mydb"    >> .env
          echo "DB_USERNAME=user"      >> .env
          echo "DB_PASSWORD=pass"      >> .env

      - name: Installer les dépendances
        run: |
          python -m pip install -U pip || python3 -m pip install -U pip
          pip install -r requirements.txt || true
          pip install pytest python-dotenv pymongo mysql-connector-python || true

      - name: Lancer les tests
        env:
          PYTHONPATH: src
        run: |
          python -m pytest -q || python3 -m pytest -q

      - name: Déploiement local
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
